<link rel="shortcut icon"
      href="https://getbootstrap.com/docs/5.3/assets/img/favicons/favicon.ico"
      type="image/x-icon" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet" />
<link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />
<link rel="stylesheet"
      href="/assets/css/style.css" />