INSERT INTO employees (first_name, last_name, email, salary, department) VALUES
('John', 'Doe', 'john.doe@example.com', 55000.00, 'Engineering'),
('Jane', 'Smith', 'jane.smith@example.com', 56000.00, 'Marketing'),
('Jim', 'Beam', 'jim.beam@example.com', 52000.00, 'Sales'),
('Jack', 'Daniels', 'jack.daniels@example.com', 53000.00, 'Human Resources'),
('Josie', 'Wales', 'josie.wales@example.com', 54000.00, 'IT'),
('Julia', 'Roberts', 'julia.roberts@example.com', 57000.00, 'Finance'),
('Jason', 'Bourne', 'jason.bourne@example.com', 58000.00, 'Legal'),
('Jennifer', 'Lawrence', 'jennifer.lawrence@example.com', 55000.00, 'Design'),
('Jake', 'Gyllenhaal', 'jake.gyllenhaal@example.com', 56000.00, 'Operations'),
('Jessica', 'Alba', 'jessica.alba@example.com', 52000.00, 'Customer Support'),
('Jeremy', 'Renner', 'jeremy.renner@example.com', 53000.00, 'Engineering'),
('Jodie', 'Foster', 'jodie.foster@example.com', 54000.00, 'Marketing'),
('Jeff', 'Bridges', 'jeff.bridges@example.com', 57000.00, 'Sales'),
('Julianne', 'Moore', 'julianne.moore@example.com', 58000.00, 'Human Resources'),
('Jonah', 'Hill', 'jonah.hill@example.com', 55000.00, 'IT'),
('James', 'Franco', 'james.franco@example.com', 56000.00, 'Finance'),
('Javier', 'Bardem', 'javier.bardem@example.com', 52000.00, 'Legal'),
('Joaquin', 'Phoenix', 'joaquin.phoenix@example.com', 53000.00, 'Design'),
('Joseph', 'Gordon-Levitt', 'joseph.gordonlevitt@example.com', 54000.00, 'Operations'),
('Jennifer', 'Connelly', 'jennifer.connelly@example.com', 57000.00, 'Customer Support');
